version: '2'
services:
  # Standard nginx image
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      # For LetsEncrypt to work, it needs to share a folder with Ceen
      - ./www.example.com:/usr/share/nginx/html

  # Docker proxy handler for nginx
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    restart: unless-stopped
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

  # LetsEncrypt support for nginx
  nginxletsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
      - nginx-gen
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  # Ceenhttdp, based on standard Mono image
  ceenrunner-mono:
    image: mono
    container_name: ceenrunnermono
    restart: unless-stopped
    
    # Use this line if you want to run the server as root
    #command: mono /usr/share/ceen/NetFullRunner.exe /usr/share/ceen/config.txt

    # Otherwise, this runs ceen with a non-privileged user
    command: start-non-root.sh mono /usr/share/ceen/NetFullRunner.exe /usr/share/ceen/config.txt

    ports:
      - "8080:8080"
    volumes:
      - ./www.example.com:/usr/share/www.example.com
      - ./ceen-mono:/usr/share/ceen
    environment:
      - LISTEN_PORT=8080
      - STORAGE_FOLDER=/usr/share/www.example.com
      - HTTPS_METHOD=redirect
      - VIRTUAL_HOST=www.example.com
      - LETSENCRYPT_HOST=www.example.com
      - LETSENCRYPT_EMAIL=email@example.com

# Ceenhttdp, based on standard .Net core image
  ceenrunner-netcore:
    image: microsoft/dotnet
    container_name: ceenrunnernetcore
    restart: unless-stopped
    
    # Use this line if you want to run the server as root
    #command: dotnet /usr/share/ceen/NetCoreRunner.dll /usr/share/ceen/config.txt

    # Otherwise, this runs ceen with a non-privileged user
    command: start-non-root.sh dotnet /usr/share/ceen/NetCoreRunner.dll /usr/share/ceen/config.txt

    ports:
      - "8080:8080"
    volumes:
      - ./www.example.com:/usr/share/www.example.com
      - ./ceen-netcore:/usr/share/ceen
    environment:
      - LISTEN_PORT=8080
      - STORAGE_FOLDER=/usr/share/www.example.com
      - HTTPS_METHOD=redirect
      - VIRTUAL_HOST=www.example.com
      - LETSENCRYPT_HOST=www.example.com
      - LETSENCRYPT_EMAIL=email@example.com
